[workspace]
authors = ["Neppel Elian <elian.neppel@posteo.eu>"]
channels = ["https://prefix.dev/conda-forge"]
name = "newton-dls"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.11.0,<3.15"


[environments]
default = { features = ["isaac"] }
dev = { features = ["isaac", "dev"] }
# newton = { features = ["newton"] }

[activation.env]
TERM = "xterm-256color" # fix for ghostty terminal emulator
NEWTON_CACHE_PATH = "./newton_cache"
RMW_IMPLEMENTATION=""
ROS_DOMAIN_ID="13"
ROS_AUTOMATIC_DISCOVERY_RANGE="LOCALHOST"
ROS_LOCALHOST_ONLY=""


[system-requirements]
cuda = "12.8"
libc="2.35"


[feature.isaac.tasks]
isaaclab="bash ./deps/IsaacLab/isaaclab.sh"

[feature.isaac.dependencies]
python = "3.12.*"
pip = "*"
# git = "*"
# gcc = "11.*"
# c-compiler = "*"
# cxx-compiler = "*"
# make = "*"
# cmake = "*"
# pkg-config = "*"

### ISAACLAB pinned deps conflict ###
pytorch-gpu = "==2.10.0"
torchvision = "==0.25.0"
torchaudio= "==2.10.0"
packaging = "==26.0"
jinja2 = "==3.1.5"
 numpy = "==2.3.1"
fsspec = "==2025.12.0"
filelock = "==3.20.0"
typing-extensions="==4.12.2"

[feature.isaac.pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = ["https://pypi.nvidia.com"]
index-strategy="unsafe-best-match"
no-build-isolation = ["flatdict"]
prerelease-mode = "allow"

[pypi-options.dependency-overrides]
# fucked up dependencies
starlette = "==0.49.* "
packaging = "==26.0"
pillow = "==12.1.*"
coverage = "==7.6.*"

[feature.isaac.pypi-dependencies]
isaacsim = { version = "==6.0.0.0", extras = ["all", "extscache"]}
isaaclab = { path = "./deps/IsaacLab/source/isaaclab"}
isaaclab_assets = { path = "./deps/IsaacLab/source/isaaclab_assets/"}
isaaclab_rl = { path = "./deps/IsaacLab/source/isaaclab_rl/"}
isaaclab_mimic = { path = "./deps/IsaacLab/source/isaaclab_mimic/"}
isaaclab_tasks = { path = "./deps/IsaacLab/source/isaaclab_tasks/"}
isaaclab_contrib = { path = "./deps/IsaacLab/source/isaaclab_contrib/"}
# torch = "==2.10.0"
# torchvision = "==0.25.0"
# torchaudio= "==2.10.0"


[feature.isaac.activation]

[feature.isaac.activation.env]
ISAACLAB_PATH="./deps/IsaacLab/"
RESOURCE_NAME="IsaacSim"

# [feature.newton.dependencies]
# python = "3.13.*"
# rerun-sdk = "*"
# pytorch-gpu = "*"
# mujoco = "*"
# open3d = "*"
#
# [feature.newton.pypi-dependencies]
# asyncio-for-robotics = ">=1.3.5, <2"
# newton = {path="deps/newton/", editable=false, extras=["examples"]}
# newton_dls = {path=".", editable=true}

[feature.dev.dependencies]
### ISAACLAB pinned deps conflict ###

uv = "*"
pyright = "*"
isort = "*"
black = "*"
glow-md = ">=2.1.1,<3"
