[workspace]
authors = ["Neppel Elian <elian.neppel@posteo.eu>"]
channels = ["https://prefix.dev/conda-forge"]
name = "newton-dls"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.11.0,<3.15"


[environments]
default = { features = ["newton", "dev"] }
# newton = { features = ["newton"] }

[activation.env]
TERM = "xterm-256color" # fix for ghostty terminal emulator
NEWTON_CACHE_PATH = "./newton_cache"
RMW_IMPLEMENTATION=""
ROS_DOMAIN_ID="13"
ROS_AUTOMATIC_DISCOVERY_RANGE="LOCALHOST"
ROS_LOCALHOST_ONLY=""


[system-requirements]
cuda = "13.0"
libc="2.35"

[feature.newton.dependencies]
python = "3.13.*"
rerun-sdk = "*"
pytorch-gpu = "*"
mujoco = "*"
open3d = "*"

[feature.newton.pypi-dependencies]
asyncio-for-robotics = ">=1.3.5, <2"
newton = {path="deps/newton/", editable=false, extras=["examples"]}
newton_dls = {path=".", editable=true}

[feature.dev.dependencies]

uv = "*"
pyright = "*"
isort = "*"
black = "*"
glow-md = ">=2.1.1,<3"
